# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_main)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_top_btns.setStyleSheet("background-color: rgba(33, 37, 43, 150);")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"margin-left: 5px;")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout.addWidget(self.frame_top_btns)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.frame_center)
        self.verticalFrame.setObjectName("verticalFrame")
        self.frame_content = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.frame_content.setSpacing(0)
        self.frame_content.setObjectName("frame_content")
        self.label = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding:10px 35px;\n"
"}\n"
"QLabel:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLabel:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}r")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.frame_content.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding:10px 35px;\n"
"}\n"
"QLabel:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLabel:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}r")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.frame_content.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.frame_content.addItem(spacerItem)
        self.gridFrame = QtWidgets.QFrame(self.verticalFrame)
        self.gridFrame.setStyleSheet("")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 4, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 38px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 5, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 8, 3, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 25px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 9, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 8, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 4, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 9, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 5, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 8, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 28px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 3, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 5, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 4, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridFrame)
        self.pushButton_11.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 37px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 3, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 37px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 9, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 8, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"\n"
"  padding: 10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
" \n"
"    background: #4285f4;\n"
"    color: #fff;\n"
"    border: 1px solid #4285f4;\n"
"    border-radius: 4px;background: #4285f4;\n"
"    color: #fff;\n"
"    border: 1px solid #4285f4;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {background-color: #8CC7DF}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 9, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"  display: inline-block;\n"
"\n"
"  padding:10px 35px;\n"
"\n"
"  font-size: 24px;\n"
"\n"
"  cursor: pointer;\n"
"\n"
"  text-align: center;\n"
"\n"
"  text-decoration: none;\n"
"\n"
"  outline: none;\n"
"\n"
"  background: #f1f3f4;\n"
"  color: #202124;\n"
"  border: 1px solid #f1f3f4;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #8CC7DF}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 5, 2, 1, 1)
        self.frame_content.addWidget(self.gridFrame)
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.verticalLayout.addWidget(self.frame_center)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_main)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_size_grip.setStyleSheet("QSizeGrip {\n"
"    background-image: url(:/16x16/icons/16x16/cil-size-grip.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.verticalLayout.addWidget(self.frame_size_grip)
        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HESAP MAKİNESİ"))
        self.label_title_bar_top.setText(_translate("MainWindow", "HESAP MAKİNESİ"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.pushButton_8.setText(_translate("MainWindow", "*"))
        self.pushButton_6.setText(_translate("MainWindow", "-"))
        self.pushButton_5.setText(_translate("MainWindow", "+"))
        self.pushButton_20.setText(_translate("MainWindow", "+/-"))
        self.pushButton_19.setText(_translate("MainWindow", "1"))
        self.pushButton_12.setText(_translate("MainWindow", "8"))
        self.pushButton_15.setText(_translate("MainWindow", "0"))
        self.pushButton_13.setText(_translate("MainWindow", "5"))
        self.pushButton_14.setText(_translate("MainWindow", "2"))
        self.pushButton_16.setText(_translate("MainWindow", "AC"))
        self.pushButton_18.setText(_translate("MainWindow", "4"))
        self.pushButton_17.setText(_translate("MainWindow", "7"))
        self.pushButton_11.setText(_translate("MainWindow", "("))
        self.pushButton_7.setText(_translate("MainWindow", "/"))
        self.pushButton_10.setText(_translate("MainWindow", ","))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", ")"))
        self.pushButton_2.setText(_translate("MainWindow", "="))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton.setText(_translate("MainWindow", "6"))
import files_rc
